package com.tunnelcheck.app.ui

import com.tunnelcheck.app.domain.model.ResultFilter

data class AppText(
    val dashboard: String,
    val quick: String,
    val bulk: String,
    val history: String,
    val export: String,
    val settings: String,
    val tested: String,
    val ready: String,
    val risky: String,
    val quickTest: String,
    val ipOrDomain: String,
    val ports: String,
    val run: String,
    val cancel: String,
    val bulkScan: String,
    val importFile: String,
    val pasteEndpoints: String,
    val scan: String,
    val clearHistory: String,
    val exportCenter: String,
    val exportOutput: String,
    val appearance: String,
    val theme: String,
    val system: String,
    val light: String,
    val dark: String,
    val language: String,
    val english: String,
    val farsi: String,
    val scanDefaults: String,
    val udpProbe: String,
    val quicProbe: String,
    val dnsProbe: String,
    val wsProbe: String,
    val allowInsecureCert: String,
    val retries: String,
    val timeout: String,
    val privacy: String,
    val localOnly: String,
    val noUpload: String,
    val rtt: String,
    val jitter: String,
    val loss: String,
    val stability: String,
    val confidence: String,
    val score: String,
    val falsePositiveWarning: String,
    val noValidEndpoints: String,
    val cancelled: String,
    val scanFailed: String,
    val unableToOpenFile: String,
    val unableToImportFile: String,
    val ok: String,
    val no: String,
    val filters: Map<ResultFilter, String>,
    val classifications: Map<String, String>
)

fun appText(language: AppLanguage) = when (language) {
    AppLanguage.English -> englishText
    AppLanguage.Farsi -> farsiText
}

private val englishText = AppText(
    dashboard = "Dash",
    quick = "Quick",
    bulk = "Bulk",
    history = "History",
    export = "Export",
    settings = "Settings",
    tested = "Tested",
    ready = "Ready",
    risky = "Risky",
    quickTest = "Quick Test",
    ipOrDomain = "IP or domain",
    ports = "Ports",
    run = "Run",
    cancel = "Cancel",
    bulkScan = "Bulk Scan",
    importFile = "Import file",
    pasteEndpoints = "Paste txt, csv, or json endpoints",
    scan = "Scan",
    clearHistory = "Clear history",
    exportCenter = "Export Center",
    exportOutput = "Export output",
    appearance = "Appearance",
    theme = "Theme",
    system = "System",
    light = "Light",
    dark = "Dark",
    language = "Language",
    english = "English",
    farsi = "Farsi",
    scanDefaults = "Scan defaults",
    udpProbe = "UDP probe",
    quicProbe = "QUIC / HTTP3 probe",
    dnsProbe = "DNS probe",
    wsProbe = "WebSocket probe",
    allowInsecureCert = "Allow insecure TLS certificates",
    retries = "Retries",
    timeout = "Timeout",
    privacy = "Privacy",
    localOnly = "Local only, no telemetry",
    noUpload = "Endpoint feeds are user-approved imports only. WhiteDns TC does not upload scan results or run background discovery.",
    rtt = "RTT",
    jitter = "Jitter",
    loss = "Loss",
    stability = "Stability",
    confidence = "Confidence",
    score = "Score",
    falsePositiveWarning = "False positive risk: open port did not prove protocol usability.",
    noValidEndpoints = "No valid endpoints found",
    cancelled = "Cancelled",
    scanFailed = "Scan failed",
    unableToOpenFile = "Unable to open selected file",
    unableToImportFile = "Unable to import file",
    ok = "OK",
    no = "NO",
    filters = mapOf(
        ResultFilter.All to "All",
        ResultFilter.TunnelReady to "Tunnel Ready",
        ResultFilter.TlsCapable to "TLS capable",
        ResultFilter.WebSocketSupported to "WebSocket",
        ResultFilter.LowLatency to "Low latency",
        ResultFilter.HighStability to "High stability"
    ),
    classifications = mapOf(
        "Tunnel Ready" to "Tunnel Ready",
        "Partially Usable" to "Partially Usable",
        "Unstable" to "Unstable",
        "Blocked" to "Blocked",
        "False Positive" to "False Positive"
    )
)

private val farsiText = AppText(
    dashboard = "خانه",
    quick = "سریع",
    bulk = "گروهی",
    history = "تاریخچه",
    export = "خروجی",
    settings = "تنظیمات",
    tested = "آزمایش شده",
    ready = "آماده",
    risky = "پرریسک",
    quickTest = "تست سریع",
    ipOrDomain = "آی‌پی یا دامنه",
    ports = "پورت‌ها",
    run = "اجرا",
    cancel = "لغو",
    bulkScan = "اسکن گروهی",
    importFile = "وارد کردن فایل",
    pasteEndpoints = "فهرست txt، csv یا json را وارد کنید",
    scan = "اسکن",
    clearHistory = "پاک کردن تاریخچه",
    exportCenter = "مرکز خروجی",
    exportOutput = "متن خروجی",
    appearance = "نمایش",
    theme = "پوسته",
    system = "سیستم",
    light = "روشن",
    dark = "تاریک",
    language = "زبان",
    english = "انگلیسی",
    farsi = "فارسی",
    scanDefaults = "پیش‌فرض‌های اسکن",
    udpProbe = "آزمون UDP",
    quicProbe = "آزمون QUIC / HTTP3",
    dnsProbe = "آزمون DNS",
    wsProbe = "آزمون WebSocket",
    allowInsecureCert = "پذیرش گواهی TLS نامعتبر",
    retries = "تکرارها",
    timeout = "مهلت انتظار",
    privacy = "حریم خصوصی",
    localOnly = "فقط محلی، بدون تله‌متری",
    noUpload = "فیدهای نقطه پایانی فقط با تایید کاربر وارد می‌شوند. WhiteDns TC نتیجه اسکن را آپلود نمی‌کند و کشف پنهانی انجام نمی‌دهد.",
    rtt = "تاخیر",
    jitter = "نوسان",
    loss = "افت",
    stability = "پایداری",
    confidence = "اطمینان",
    score = "امتیاز",
    falsePositiveWarning = "خطر مثبت کاذب: باز بودن پورت به تنهایی کاربرد پروتکل را ثابت نمی‌کند.",
    noValidEndpoints = "نقطه پایانی معتبری پیدا نشد",
    cancelled = "لغو شد",
    scanFailed = "اسکن ناموفق بود",
    unableToOpenFile = "امکان باز کردن فایل انتخاب‌شده وجود ندارد",
    unableToImportFile = "امکان وارد کردن فایل وجود ندارد",
    ok = "بله",
    no = "خیر",
    filters = mapOf(
        ResultFilter.All to "همه",
        ResultFilter.TunnelReady to "آماده تونل",
        ResultFilter.TlsCapable to "دارای TLS",
        ResultFilter.WebSocketSupported to "WebSocket",
        ResultFilter.LowLatency to "تاخیر کم",
        ResultFilter.HighStability to "پایداری بالا"
    ),
    classifications = mapOf(
        "Tunnel Ready" to "آماده تونل",
        "Partially Usable" to "قابل استفاده نسبی",
        "Unstable" to "ناپایدار",
        "Blocked" to "مسدود",
        "False Positive" to "مثبت کاذب"
    )
)
